### ISSUE TITLE
codecov doesn't exit with error if upload fails

### ISSUE THREAD

**Issue by meetmangukiya** [codecov/codecov-python#103]

**Comment by meetmangukiya** [comment]
Example : https://semaphoreci.com/coala/corobo/branches/meet-plug-github/builds/1

```
      _____          _
     / ____|        | |
    | |     ___   __| | ___  ___ _____   __
    | |    / _ \ / _  |/ _ \/ __/ _ \ \ / /
    | |___| (_) | (_| |  __/ (_| (_) \ V /
     \_____\___/ \____|\___|\___\___/ \_/
                                    v2.0.9

==> Detecting CI provider
    Semaphore Detected
==> Preparing upload
Error: Missing repository upload token

Tip: See all example repositories: https://github.com/codecov?query=example
Support channels:
  Email:   hello@codecov.io
  IRC:     #codecov
  Gitter:  https://gitter.im/codecov/support
  Twitter: @codecov
```

**Comment by zchee** [comment]
@meetmangukiya It seems to codecov-python's bug.
Solution is add `--file /path/to/coveragefile` to `codecov` command. actually, in Go:

```sh
go test -v -race -coverprofile=coverage.txt -covermode=atomic ./... # coverage.txt is cover file
.
.
codecov --file coverage.txt
```

/cc @stevepeak

**Comment by stevepeak** [comment]
The file path coverage.txt should be detected without any issues. Are you using Docker to test? Maybe the file is inside the container and not passed out of it.

**Comment by stevepeak** [comment]
We will continue to use `exit 0` by default because if your CI passes it should remain passed regardless of Codecov. Use `-Z` to change this behavior.

**Comment by scott-estes** [comment]
@stevepeak can you give a 1 line example of using the -Z, as it's coming back with 
`codecov: error: unrecognized arguments: -Z` for me

**Comment by xoxys** [comment]
Quiet old thread but for completion, the currently used parameter is `--required`

```
codecov --help | grep exit
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  --required            If Codecov fails it will exit 1 - possibly failing the
```
