### ISSUE TITLE
Impossible to obtain the badge for a specific branch

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [codecov/codecov-python#109]
Hello,

I ma using codecov for a Django Project, and I can't manage to find the badge's url for a specific URL, it  doesn't work whatever address I try to use:
- branch: dev
- repository: https://github.com/DEKHTIARJonathan/FeedCrunch.IO/
- codecov link: https://codecov.io/gh/DEKHTIARJonathan/FeedCrunch.IO

Some url tried:
- https://img.shields.io/codecov/c/github/DEKHTIARJonathan/FeedCrunch.IO/dev.svg 
![](https://img.shields.io/codecov/c/github/DEKHTIARJonathan/FeedCrunch.IO/dev.svg)
- https://codecov.io/gh/DEKHTIARJonathan/FeedCrunch.IO/branch/master/graph/badge.svg 
![](https://codecov.io/gh/DEKHTIARJonathan/FeedCrunch.IO/branch/dev/graph/badge.svg)

Anyone knows why it doesn't work ?

The branch exists on codecov without any issue:
![image](https://user-images.githubusercontent.com/10923599/30553912-f17e4716-9ca2-11e7-9e38-5dcdb96ec5c8.png)

Thanks a lot

**Comment by stevepeak** [comment]
Issue with our cache. The badges for both branches work now. Thank you!

https://codecov.io/gh/DEKHTIARJonathan/FeedCrunch.IO/branch/dev/graphs/badge.svg
https://codecov.io/gh/DEKHTIARJonathan/FeedCrunch.IO/branch/master/graphs/badge.svg
