### ISSUE TITLE
C++ / gcov: Incorrect file paths

### ISSUE THREAD

**Issue by chfast** [codecov/codecov-python#110]
This is about a C++ project.

Previously I was using lcov script to collect and filter coverage data. As the result I had single `coverage.data` file uploaded with `codecov -f` bash script.

Now I switched to codecov-python and I'd like to collect gcov data directly with the script.
The biggest issue is the script is not able to recognize the file location correctly. In the result the same files are listed twice - once in the correct directory, once in project root dir.

PR: https://github.com/ethereum/cpp-ethereum/pull/4526
Report: https://codecov.io/gh/ethereum/cpp-ethereum/tree/6018d53addb1a0a66cdd011e21887ca53f4a7f02
Example file AES.cpp:
https://codecov.io/gh/ethereum/cpp-ethereum/src/6018d53addb1a0a66cdd011e21887ca53f4a7f02/libdevcrypto/AES.cpp
https://codecov.io/gh/ethereum/cpp-ethereum/src/6018d53addb1a0a66cdd011e21887ca53f4a7f02/AES.cpp (file not found).

**Comment by stevepeak** [comment]
Found to be repo specific. Contacting customer directly.
