### ISSUE TITLE
Allow selection of the coverage report filename

### ISSUE THREAD

**Issue by 13steinj** [codecov/codecov-python#111]
coverage.py allows for one to choose the filename (defaulting to .coverage). Because of the regexes, some of the possible variations in filenames are not detected (in a project that I recently worked on, the format `.coverage.anywordhere`) was not detected (coverage.py allows variable substitution from the os environment in its configuration and anywordhere was being substituted as either unit or functional depending on the build, for context).

While I've solved my own problem by reordering the format in the config to be `${ENV_VAR}.coverage`; which is just as fine to me, others may want some other naming scheme for a variety of purposes.

A simple CLI argument specifying which report to collect and upload would suffice (this would run instead of the collect reports section)

**Comment by stevepeak** [comment]
The file's at `.coverage.foobar` are generated by `coveragepy` and do not container mapped coverage information. The details of these files must be generated into the `coverage.xml` file via `$ coverage xml` command.
