### ISSUE TITLE
Reports /bin/sh: 1: coverage: not found when using Debian packages.

### ISSUE THREAD

**Issue by cheako** [codecov/codecov-python#113]
https://travis-ci.org/cheako/Tor2web-1/builds/285180144#L1782

Debian installs coverage to python-coverage.  A command line option would be a simple solution, but ideally in shell one would do something like...
```
COVERAGE=false
[ "`type -t coverage`" ] && COVERAGE=coverage
[ "`type -t python-coverage`" ] && COVERAGE=python-coverage
[ "$COVERAGE" == false ] && echo "No coverage, all calls will fail."

$COVERAGE xml -i
```

**Comment by thomasrockhu** [comment]
I'm going to close this out due to age, but if this is still a need, please open an issue on our [community boards](https://community.codecov.io)

**Comment by cheako** [comment]
Don't know why u'd think this being old means...  What does that mean?

https://packages.debian.org/buster/amd64/python-coverage/filelist

Yes, very much still installed under another name.

**Comment by thomasrockhu** [comment]
@cheako I think this is the [coverage.py](https://coverage.readthedocs.io/en/coverage-5.5/) package, not Codecov from the link you sent

**Comment by cheako** [comment]
There is no debian package that installs an application called `coverage`.  So calling an application by that name is incorrect, in the case where the application is installed by debian package.

I've tested the origin post's code, above, and it is correct.
