### ISSUE TITLE
Amazon S3 Reduced Redundancy costs more than Standard

### ISSUE THREAD

**Issue by SethMichaelLarson** [codecov/codecov-python#119]
Amazon isn't keeping Reduced Redundancy to be cheaper than Stardand storage. It actually costs more for less data durability. Should codecov be changed to use Standard storage?

**Comment by stevepeak** [comment]
Hey! Thank you for opening this issue.

Can you link me to the pages that suggest it is not less expensive?
I've done some review on my own which suggests you are correct, but I want to make sure. 

Thanks!

**Comment by stevepeak** [comment]
Thanks! Moving this package and others to not use reduced.

**Comment by SethMichaelLarson** [comment]
Sorry for not replying earlier! Must have gotten lost in my GitHub notifications. Glad everything worked out :tada:
