### ISSUE TITLE
coveragerc data_file parameter is not working

### ISSUE THREAD

**Issue by moylop260** [codecov/codecov-python#120]
Steps to reproduce it:
 - Create a [.coveragerc using the following parameter](https://github.com/OCA/maintainer-quality-tools/blob/2bb8c9b70ee28675f7afcdc731113bf014ca6a30/.coveragerc#L1-L2):
```conf
[run]
data_file = .coverage_custom
...
```
 - Run [`coverage run` command](https://github.com/OCA/maintainer-quality-tools/blob/2bb8c9b70ee28675f7afcdc731113bf014ca6a30/.travis.yml#L69-L70)
 - Check that the file `.coverage_custom` is created fine running `coverage report -m`
 - Run [`codecov` command](https://github.com/OCA/maintainer-quality-tools/blob/2bb8c9b70ee28675f7afcdc731113bf014ca6a30/travis/travis_after_tests_success#L19)

Saw:
 - [Error: No coverage report found](https://travis-ci.org/OCA/maintainer-quality-tools/jobs/295502249#L958)

Expected:
 - Report uploaded

**Comment by stevepeak** [comment]
Thank you for reporting. However, coveragepy is responsible for the `.coveragerc` file before Codecov comes into play.

Can you try this to replicate without Codecov

```sh
coverage run ...
coverage xml
```
