### ISSUE TITLE
AppVeyor public repo needs token for upload

### ISSUE THREAD

**Issue by horenmar** [codecov/codecov-python#123]
I spent some time tearing my hair out on this, but using `codecov` installed from `pip`, uploading from AppVeyor [fails](https://ci.appveyor.com/project/CatchOrg/catch2/build/dev-appveyor-coverage%20-%2021aff88020c8552a870ee46681c8fe51eb6f2b06/job/y79hs3cajglwfqed), but if I provide token manually, it [succeeds](https://ci.appveyor.com/project/CatchOrg/catch2/build/job/9667p1i7wqcm7h69).

I am using pip-installed version 2.0.9

**Comment by stevepeak** [comment]
Sorry about this issue. I see a couple upload attempts. One with the python uploader and another with the bash.

There is an issue using the AppVeyor API. The format of some variables appear to have changed in AppVeyor that I need to review. I believe I have already found the issue and will deploy a patch to check it out.

**Comment by jherby2k** [comment]
@stevepeak this has been an issue for a long time... any chance at getting this released?

**Comment by thomasrockhu** [comment]
I'm going to close this out due to age, but if this is still a need, please open an issue on our [community boards](https://community.codecov.io)
