### ISSUE TITLE
The result of coverage reports doesn't match that of codecov at all.

### ISSUE THREAD

**Issue by thautwarm** [codecov/codecov-python#125]
[The result of command `coverage report`](https://travis-ci.org/thautwarm/Linq.py/jobs/318643137).
```bash
0.31s$ coverage report

Name                         Stmts   Miss  Cover

------------------------------------------------

linq/__init__.py                 3      0   100%

linq/core/__init__.py            0      0   100%

linq/core/flow.py               37      3    92%

linq/core/utils.py              30      7    77%

linq/standard/__init__.py        6      0   100%

linq/standard/dict.py            3      0   100%

linq/standard/general.py       179      8    96%

linq/standard/generator.py       6      0   100%

linq/standard/list.py           29      0   100%

linq/standard/set.py             9      0   100%

test.py                         41      0   100%

------------------------------------------------

TOTAL                          343     18    95%
```

However, I was quite annoyed by [this result](https://codecov.io/gh/thautwarm/Linq.py) and it didn't change at all after a big commit.
The analysis of `codecov` even tells me that I do not run a function after I do have run this function. 
For instance, the red area of [this file](https://codecov.io/gh/thautwarm/Linq.py/src/master/linq/standard/general.py) makes me even wanna burst into laughing.  
Oh dear, It's not necessary to mark an empty line as `unreached`...   
Could you please help me with this problem?

**Comment by dev-zero** [comment]
The problem seems to be files with the same name but in different packages. Take as an example https://codecov.io/gh/aiidateam/aiida_core/branch/develop with the following files:

* `aiida/plugins/utils.py`
* `aiida/work/utils.py`
* `aiida/common/utils.py`

of those, only `aiida/plugins/utils.py` shows up on Codecov, while the rest are completely omitted.

**Comment by thomasrockhu** [comment]
I'm going to close this out due to age, but if this is still a need, please open an issue on our [community boards](https://community.codecov.io)
