### ISSUE TITLE
Revert #118

### ISSUE THREAD

**Issue by njsmith** [codecov/codecov-python#127]
The change made in #118 looks good on the surface, but completely changed the meaning of the code and broke it :-). See https://github.com/codecov/codecov-bash/issues/106

Anyone with write access to this repo should be able to do this trivially by clicking the "revert" button in #118's history.

CC: @blueyed @stevepeak

**Comment by skirpichev** [comment]
[Here](https://travis-ci.org/diofant/diofant/jobs/324170971) is an example of CI build, where after "fixing merge commit" by codecov utility - coverage stats submitted to completely wrong URI.

**Comment by blueyed** [comment]
Reverted in https://github.com/codecov/codecov-python/commit/7f53af7b60dfbf0a05e8a885bc5519af4489a615.

**Comment by skirpichev** [comment]
btw, probably this issue could be closed
