### ISSUE TITLE
Error when running codecov -f $resolvedResultFile -X gcov

### ISSUE THREAD

**Issue by johlju** [codecov/codecov-python#129]
We have started seeing an error a couple of weeks back when running the following (in AppVeyor using PowerShell script). It seems this is an error that get reported in the Python code for codecov (it is not a native PowerShell error message). 
Was hoping for some insight what could be going on. 

I more detailed write up can be seen in the issue https://github.com/PowerShell/DscResource.Tests/issues/203.

```
$null = pip install git+git://github.com/codecov/codecov-python.git
uploadResults = codecov -f $resolvedResultFile -X gcov
```

```
codecov : The filename, directory name, or volume label syntax is incorrect.
At C:\projects\xnetworking\DscResource.Tests\DscResource.CodeCoverage\CodeCovIo.psm1:336 char:22
+     $uploadResults = codecov -f $resolvedResultFile -X gcov
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The filename, d...x is incorrect.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```
See test run here: https://ci.appveyor.com/project/PowerShell/xnetworking/build/3.1.786.0#L4671

**Comment by johlju** [comment]
See [comment](https://github.com/PowerShell/DscResource.Tests/issues/203#issuecomment-358130148) how this was workaround by commenting out [this row](https://github.com/codecov/codecov-python/commit/d8f9c7bcbf3217be472bd9295934dab4ff31bb7c#diff-ed4cb86e1f4a5c5feeecc37b90ec6a23R557).

I'm not familiar with Python so I don't know how to solve this one, but happy to send in a PR if someone know how this can be solved.

**Comment by thomasrockhu** [comment]
@johlju if this is still an issue, please feel free to open a ticket in our [community boards](https://community.codecov.io).
