### ISSUE TITLE
Upload failure:  'ascii' codec can't decode

### ISSUE THREAD

**Issue by chfast** [codecov/codecov-python#130]
```
==> Uploading
    .url https://codecov.io
    .query service=circleci&package=py2.0.11&yaml=codecov.yml&job=2049.0&build=2049.0&branch=lll&commit=22110560b5107497a72d0888b70fa7b8d8f128e8&slug=ethereum%2Fcpp-ethereum
    Pinging Codecov...
    Uploading to S3...
Error: 'ascii' codec can't decode byte 0xe2 in position 12947300: ordinal not in range(128)
```

Example build: https://circleci.com/gh/ethereum/cpp-ethereum/2049.

**Comment by stevepeak** [comment]
@blueyed this consistently is an issue that I have a hard time resolving. Are you able to shed light on a way to fix this for good?

**Comment by stevepeak** [comment]
We believe this line is causing the issue https://github.com/codecov/codecov-python/blob/f6cd01a312df45024766c50851957cb7b6f78c8d/codecov/__init__.py?utf8=%E2%9C%93#L723

TBO I'm not experienced enough to figure out how to resolve encoding issues (I've lost sleep trying to figure them out). @blueyed can you help out here?

**Comment by blueyed** [comment]
@stevepeak 
Please tag `v2.0.11`.

@chfast 
Is https://circleci.com/gh/ethereum/cpp-ethereum/2049 using Python 2 or 3?

I guess it is Python 2, which fails when using `encode` on a non-unicode string?
```
>>> s = 'ä'
>>> s.encode('utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
>>> s = u'ä'
>>> s.encode('utf-8')
'\xc3\xa4'
```

With Python 3:
```
>>> s = 'ä'
>>> s.encode('utf-8')
b'\xc3\xa4'
>>> s = u'ä'
>>> s.encode('utf-8')
b'\xc3\xa4'
```

**Comment by blueyed** [comment]
@chfast 
You can use `--dump` to get more information (the actual report).
And you could use codecov-bash always to make it work for now, but we should get this fixed of course.

**Comment by chfast** [comment]
codecov-bash is much worse.
I use whatever installed, probably python 2.

Of course 
```
>>> s = 'ä'
>>> s.encode('utf-8')
```
does not work in Python 2. `'ä'` means bytes, to get unicode string out of it you have to decode it `s.decode('utf-8')`. I have no idea what "encode" means in this case.

**Comment by blueyed** [comment]
@chfast 
> codecov-bash is much worse.

What do you mean?  Doesn't it work for you?

**Comment by chfast** [comment]
Hopefully fixed by #133.

> @chfast
> 
> codecov-bash is much worse.
> 
> What do you mean? Doesn't it work for you?

codecov-bash is

1. Much slower than codecov-python. Getting gcov data takes minutes instead of seconds.
2. Does not work on Windows.
3. I can fix Python. I don't want fixing bash scripts.

**Comment by stevepeak** [comment]
@chfast Deployed in v2.0.13

I wonder what's making the bash version gcov scripts slow.

**Comment by chfast** [comment]
@stevepeak I wonder that too...

Fixed in https://github.com/codecov/codecov-python/pull/133.
Released in v2.0.13.

**Comment by blueyed** [comment]
The gcov execution looks similar, but with codecov-python some files/dirs are excluded: https://github.com/codecov/codecov-python/blob/1d77b8f592a24ea1e6a4ab4c9010b3e2cacdb035/codecov/__init__.py#L602
Here is the bash one: https://github.com/codecov/codecov-bash/blob/5d400d650cdd449aad8e7d3f8949d8aef9303a58/codecov#L936

**Comment by blueyed** [comment]
Ah, they should be ignored in codecov-bash, too: https://github.com/codecov/codecov-bash/blob/5d400d650cdd449aad8e7d3f8949d8aef9303a58/codecov#L30.

**Comment by stevepeak** [comment]
These were recent additions. So perhaps the two processing agents are equal in speed and strategy.
