### ISSUE TITLE
Regression in v2.0.13: running "coverage combine" overrides existing .coverage

### ISSUE THREAD

**Issue by lesteve** [codecov/codecov-python#135]
After I run `pytest` with coverage enabled (through `--cov` option),  I have some empty ill-formatted `.coverage.*` files (I will not go into details why, I am not 100% sure exactly, probably this has to do with `Pool.join` not being called in some places).

An example of .coverage* files I have after the `pytest --cov` run (taken from this Travis [log](https://travis-ci.org/lesteve/joblib/jobs/329948292#L2239)):
```
-rw-r--r-- 1 travis travis    0 Jan 17 16:49 .coverage.travis-job-lesteve-joblib-329948292.travisci.net.2842.950710
-rw-r--r-- 1 travis travis    0 Jan 17 16:50 .coverage.travis-job-lesteve-joblib-329948292.travisci.net.3588.085891
-rw-r--r-- 1 travis travis  22K Jan 17 16:52 .coverage
-rw-r--r-- 1 travis travis 2.6K Jan 17 16:52 .coverage.travis-job-lesteve-joblib-329948292.travisci.net.5223.980799
```

Since v2.0.13 (and this [commit](https://github.com/codecov/codecov-python/commit/6354ac225a9413cc19d6418e4829d9376d22ad14#diff-ed4cb86e1f4a5c5feeecc37b90ec6a23)), `coverage combine` is run under the hood by `codecov`. In a setup like mine this will override the existing `.coverage` and result in partial coverage (actually in my case the coverage drop to near zero, because the .coverage.* are very small).

I tried to call `coverage combine -a` before calling `codecov` and that fixes the issue, so you probably want to do that (as well as in the bash tool) unless there is something I am missing.

**Comment by stevepeak** [comment]
Deploying a patch today. Thank

**Comment by lesteve** [comment]
Thanks at lot! Not 100% sure how codecov-python and codecov-bash are synchronized but you may want to update similar lines in codecov-bash:
https://github.com/codecov/codecov-bash/blob/a269d9322355c8cf83b97c8dedeb786c0dce2e90/codecov#L953-L958

**Comment by stevepeak** [comment]
Thanks! I'll update the bash uploader too.
