### ISSUE TITLE
__init__.py files not covered

### ISSUE THREAD

**Issue by MatthieuGouel** [codecov/codecov-python#136]
Hello ! 

I just tested codecov on one of my Python project.
All my files are correctly present in the file coverage.xml but in the website the __init__.py files are not present. This lead to false the code coverage.
 I don't have a codecov.yml file on my project.

My CI build use codecov 2.0.15

Is it a choice not to include __ init __.py files ?

Here is my [coverage report ](https://codecov.io/gh/MatthieuGouel/python-flask-api-skeleton).
And the coverage.xml file :
```
<?xml version="1.0" ?>
<coverage branch-rate="0" branches-covered="0" branches-valid="0" complexity="0" line-rate="1" lines-covered="59" lines-valid="59" timestamp="1517859076385" version="4.5">
	<!-- Generated by coverage.py: https://coverage.readthedocs.io -->
	<!-- Based on https://raw.githubusercontent.com/cobertura/web/master/htdocs/xml/coverage-04.dtd -->
	<sources>
		<source>/Users/matthieu/Documents/Informatique/python/flask-api-skeleton/api</source>
	</sources>
	<packages>
		<package branch-rate="0" complexity="0" line-rate="1" name=".">
			<classes>
				<class branch-rate="0" complexity="0" filename="__init__.py" line-rate="1" name="__init__.py">
					<methods/>
					<lines>
						<line hits="1" number="3"/>
						<line hits="1" number="9"/>
						<line hits="1" number="12"/>
						<line hits="1" number="15"/>
						<line hits="1" number="17"/>
						<line hits="1" number="20"/>
						<line hits="1" number="27"/>
						<line hits="1" number="30"/>
						<line hits="1" number="33"/>
						<line hits="1" number="34"/>
						<line hits="1" number="35"/>
						<line hits="1" number="37"/>
						<line hits="1" number="40"/>
						<line hits="1" number="42"/>
						<line hits="1" number="45"/>
						<line hits="1" number="48"/>
						<line hits="1" number="51"/>
						<line hits="1" number="52"/>
						<line hits="1" number="54"/>
						<line hits="1" number="56"/>
						<line hits="1" number="58"/>
						<line hits="1" number="62"/>
						<line hits="1" number="65"/>
						<line hits="1" number="71"/>
						<line hits="1" number="74"/>
						<line hits="1" number="77"/>
					</lines>
				</class>
				<class branch-rate="0" complexity="0" filename="config.py" line-rate="1" name="config.py">
					<methods/>
					<lines>
						<line hits="1" number="2"/>
						<line hits="1" number="5"/>
						<line hits="1" number="8"/>
						<line hits="1" number="9"/>
						<line hits="1" number="10"/>
						<line hits="1" number="12"/>
						<line hits="1" number="13"/>
						<line hits="1" number="14"/>
						<line hits="1" number="17"/>
						<line hits="1" number="20"/>
						<line hits="1" number="23"/>
						<line hits="1" number="26"/>
						<line hits="1" number="27"/>
						<line hits="1" number="30"/>
						<line hits="1" number="33"/>
						<line hits="1" number="36"/>
						<line hits="1" number="39"/>
						<line hits="1" number="40"/>
						<line hits="1" number="43"/>
					</lines>
				</class>
			</classes>
		</package>
		<package branch-rate="0" complexity="0" line-rate="1" name="resources">
			<classes>
				<class branch-rate="0" complexity="0" filename="resources/__init__.py" line-rate="1" name="__init__.py">
					<methods/>
					<lines>
						<line hits="1" number="3"/>
						<line hits="1" number="4"/>
						<line hits="1" number="7"/>
						<line hits="1" number="10"/>
						<line hits="1" number="12"/>
						<line hits="1" number="15"/>
						<line hits="1" number="21"/>
					</lines>
				</class>
				<class branch-rate="0" complexity="0" filename="resources/main.py" line-rate="1" name="main.py">
					<methods/>
					<lines>
						<line hits="1" number="3"/>
						<line hits="1" number="6"/>
						<line hits="1" number="9"/>
						<line hits="1" number="10"/>
						<line hits="1" number="11"/>
						<line hits="1" number="14"/>
						<line hits="1" number="16"/>
					</lines>
				</class>
			</classes>
		</package>
	</packages>
</coverage>
```
Thanks !

**Comment by spyoungtech** [comment]
Ran into this as well. In my case, when I run `coverage`, the `__init__.py` files are included in the coverage report via `coverage report`. But my codecov reports online do not include the `__init__.py` **in the source root**. `__init__.py` files in submodules are included.

Seems related to #125

**Comment by stevepeak** [comment]
> This question is better suited for `coveragepy` or StackOverflow.

I would check your configuration to make sure they are not ignored in your `.coveragerc` http://coverage.readthedocs.io/en/coverage-4.4.2/config.html

**Comment by spyoungtech** [comment]
Thanks for the response @stevepeak apologies if this is in the wrong place or if there's something obvious I'm missing, but it seems to me that `coverage` is doing the right thing and working as expected. Even the output of `codecov --dump` seems to suggest it's working as expected. However, I'm not sure why the online report doesn't reflect this.

The contents of my `.coveragerc` are simply as follows

```
[run]
source=behave_webdriver
```

`coverage report` suggests 89% coverage and includes the `__init__.py` file. This seems to be working as expected, no issues...

```
Name                                     Stmts   Miss  Cover
------------------------------------------------------------
behave_webdriver\__init__.py               206     26    87%
behave_webdriver\conditions.py              58      5    91%
behave_webdriver\steps\__init__.py           2      0   100%
behave_webdriver\steps\actions.py           79     12    85%
behave_webdriver\steps\expectations.py     173     14    92%
------------------------------------------------------------
TOTAL                                      518     57    89%
```

`codecov --dump` [includes the file too](https://api.travis-ci.org/v3/job/339627926/log.txt) and appears to have the same correct data as `coverage`.

However, when I check the results online the first `__init__.py` appears to not be included in [the online report](https://codecov.io/gh/spyoungtech/behave-webdriver/tree/master/behave_webdriver) for some reason. This causes codecov to (seemingly erroneously) report 91% coverage instead of the expected 89% seemingly due to the loss of the first `__init__.py` file.

When browsing the offending directory online, codecov seems to still want to insist the file is there, but it's not included in the report and is not viewable.

![missing file](https://i.imgur.com/pwJLrtn.png)

Note that it says "2 files" in this directory, however there is clearly only one (it is omitting `__init__.py` for some reason.) Not clear to me why this is.

**Comment by aronisstav** [comment]
I am experiencing a similar issue but I am using:
- the bash uploader
- on an Erlang project
- after I have converted some internal coverage data to the Cobertura format
- and I am missing the first `<class>` entry, which is my case is `concuerror.erl`.
- without any ignored files

Based on these observations I would guess that the problem might be on the server side's treatment of the first entry of Cobertura reports.

**Comment by spyoungtech** [comment]
Agree it seems to be a problem with the service, not the generation of the report or tool used. The same build/tool/report uploaded to coveralls does not have the same problem.

**Comment by vdrhtc** [comment]
@spyoungtech, @aronisstav, @matthieugouel
Found this thread while searching

Maybe you could see [here](https://github.com/encode/django-rest-framework/issues/5647) and [here](https://github.com/encode/django-rest-framework/pull/5970) for the fix if it this still relevant

**Comment by MichaelKim0407** [comment]
@stevepeak please reopen this issue.

The coverage report clearly contains `__init__.py` in both local and ci tests, but they are not reported on codedev website.

**Comment by feliwir** [comment]
Was this ever fixed? Our report still contains no `__init__py`. See:
https://codecov.io/gh/OpenSAGE/OpenSAGE.BlenderPlugin/tree/master/io_mesh_w3d

**Comment by eric-wieser** [comment]
@stevepeak, can this be re-opened?

**Comment by Kogia-sima** [comment]
experiencing same issue here with **Rust + kcov**.

**Comment by postlund** [comment]
I have this problem in pyatv as well. One of my __init__.py files are ignored but the others are present. Noteworthy is that I had this file ignored before in my `.coveragerc`, but have removed it from there. Coverage for the file is in the generated report, but not on website.

**Comment by AbdealiJK** [comment]
Similar story for me ...
Just a bump to reopen the issue.

**Comment by tsiq-decker** [comment]
@stevepeak Can you re-open this issue? I believe I'm experiencing something similar. I have files that I expect to see in the Codecov Web UI, but I don't.

I also don't see files with 0% coverage (which are shown in `coverage report`) that I'd like to appear in the UI to draw attention to them.

**Comment by thomasrockhu** [comment]
@aadibajpai and @tsiq-decker can you open at ticket in the support section of our [community boards](https://community.codecov.io)?

**Comment by kernc** [comment]
It works following the **workaround** prescribed in https://community.codecov.io/t/init-py-suddenly-being-ignored-in-reports/1855, adding [path fixing](https://docs.codecov.io/docs/fixing-paths):
```yaml
# .codecov.yml:
coverage:
  ...
  fixes:
    - "__init__.py::<source>/__init__.py"
```
with `<source>` being whatever `[run] source` in _.coveragerc_ (`coverage --source`) points to.

In discord with the [reference for `fixes`](https://docs.codecov.io/docs/codecovyml-reference#fixes) which IIUC specifies it as a top-level setting, I found it only having an effect when specified as `coverage.fixes` (as above). :confused: 

-----

With only the toplevel \_\_init\_\_.py file affected, it's obvious this is something _on your end_ and that **this bug should be reopened**.
