### ISSUE TITLE
CircleCI: No .coverage file found.

### ISSUE THREAD

**Issue by rshejnberg** [codecov/codecov-python#137]
I've been having issues generating coverage reports for a Flask application in a private repository in CircleCI. I am able to do so locally by running ``codecov -t TOKEN``, however, in the CI I get the following when running the same command:

```

      _____          _
     / ____|        | |
    | |     ___   __| | ___  ___ _____   __
    | |    / _ \ / _  |/ _ \/ __/ _ \ \ / /
    | |___| (_) | (_| |  __/ (_| (_) \ V /
     \_____\___/ \____|\___|\___\___/ \_/
                                    v2.0.15

==> Detecting CI provider
    Circle CI Detected
==> Preparing upload
==> Processing gcov (disable by -X gcov)
    Executing gcov (find /home/circleci/repo -not -path './bower_components/**' -not -path './node_modules/**' -not -path './vendor/**' -type f -name '*.gcno'  -exec gcov -pb  {} +)
==> Collecting reports
Error: No coverage report found
```

I received the same error when trying to command recommended by CircleCI's [docs](https://circleci.com/docs/1.0/code-coverage/):

```
bash <(curl -s https://codecov.io/bash)
```

Seems like CodeCov is failing to generate ``coverage.xml`` on CircleCI, any ideas what could cause this?

_codecov.yml_

```
codecov:
  branch: master
coverage:
  status:
    patch: false
    project:
      default:
        target: '70'
        threshold: '0.1'
        branches: null
        only_pulls: false
```

**Comment by stevepeak** [comment]
It appears there are no `.coverage` files which are generated automatically by `coveragepy`. Please run your tests locally to make sure coverage is generated and accessible by Codecov during the upload process. 

If you are using Tox or Docker to test please follow these directions: https://github.com/codecov/codecov-python#using-tox and https://docs.codecov.io/docs/testing-with-docker

Thank you 👍
