### ISSUE TITLE
Automatic coverage file collection disabled on Appveyor

### ISSUE THREAD

**Issue by mpeterv** [codecov/codecov-python#138]
When Appveyor is detected, coverage files are not collected automatically. This seems to be intentional (d334f5c), however, it would be convenient if automatic collection did work for Appveyor. Additionally, this restriction doesn't seem to be mentioned in README.

**Comment by altendky** [comment]
@stevepeak, do you know what happened to codecov/support?  I was specifically going to mention codecov/support#402 but it has disappeared.  I don't recall there being a specific reason given for this though looking at my email apparently the powershell uploader was suggested.  Was there some reason to explicitly disable collection on AppVeyor?  Is there now?

Anyways, I ran into this a year and a half ago and worked 'around' (before) it in twisted/twisted#831 where I just pinned to `codecov==2.0.5` before that commit linked above.  Twisted is still using that.

https://github.com/twisted/twisted/blob/88e0b450f1215ac889cd3feaf4d082527c65d078/tox.ini#L55

**Comment by thomasrockhu** [comment]
I'm going to close this out due to age, but if this is still a need, please open an issue on our [community boards](https://community.codecov.io)
