### ISSUE TITLE
Error messages when running on Windows

### ISSUE THREAD

**Issue by mpeterv** [codecov/codecov-python#139]
codecov-python's own [Appveyor build](https://ci.appveyor.com/project/stevepeak/codecov-python/build/1.0.291/job/pl23ejsc65tor1a5) demonstrates the issue: error messages like ``Error running `cd 'C:\projects\codecov-python' && git ls-files`: None`` followed by `The filename, directory name, or volume label syntax is incorrect.` appear in console. Not sure what the consequences are - it seems that the build is failing for some unrelated reason as similar errors are shown for [successful builds](https://ci.appveyor.com/project/mpeterv/lua-ci-example/branch/master/job/1qv2ibrm36jvcwlv), too.

**Comment by blueyed** [comment]
1. The "Error running `cd 'C:\projects\codecov-python' && git ls-files`: None" can be ignored, but should get fixed nonetheless.
2. `find` on Windows is apparently different from POSIX find?!  It is used for gcov only though, so you can disable it with `-X gcov` (which you do already (https://ci.appveyor.com/project/mpeterv/lua-ci-example/build/1.0.5/job/1qv2ibrm36jvcwlv#L184)).

**Comment by Flamefire** [comment]
@blueyed the fix is there for a while now but not merged: https://github.com/codecov/codecov-python/pull/169

**Comment by thomasrockhu** [comment]
This has been merged.
