### ISSUE TITLE
Does codecov support multiple branches?

### ISSUE THREAD

**Issue by marlonbymendes** [codecov/codecov-python#145]
If my repo does have a `.codecov.yml` file [like this](https://github.com/marlonbymendes/2018.1-Cardinals/commit/cd37bf83c737c324f7084910ed7d087d6c607118), configured for branch `codecov`, codecov.io/ shows code coverage only for the branch `codecov`, even if I commit on other branches.

However, if my repo doesn't have the file  `.codecov.yml`, codecov.io/ will only show code coverage for the default branch on GitHub, which is `develop`. That's why I ask: Does codecov support multiple branches? How can I do so?

**Comment by stevepeak** [comment]
This branch is only used for the default branch when viewing the project dashboard. We only support one branch at time. Thanks!
