### ISSUE TITLE
Codecov doesn't update github PR status

### ISSUE THREAD

**Issue by pckroon** [codecov/codecov-python#157]
Hi all,

I'm pretty sure this is the wrong place to post this, but I don't know where else to turn.
I have a github repo [1], and run my tests using Travis CI. The results are uploaded to codecov without issues; let's take PR 96 [2] as an example. The Travis run is here: [3]. The coverage data does make it to CodeCov [4]. 
However, CodeCov does *not* post a PR status. I have a .codecov.yml [5], and I have CodeCov's GitHub webhook integration enabled for the repository. CodeCov.io detects this in the reposettings. 
I'm at a loss at what to try next; does anyone have an idea?

Peter

[1] https://github.com/marrink-lab/vermouth-martinize/
[2] https://github.com/marrink-lab/vermouth-martinize/pull/96
[3] https://travis-ci.org/marrink-lab/vermouth-martinize/jobs/421973707
[4] https://codecov.io/gh/marrink-lab/vermouth-martinize/pull/96
[5] https://github.com/marrink-lab/vermouth-martinize/blob/master/.codecov.yml

**Comment by bryantee** [comment]
Having the same issue

**Comment by pckroon** [comment]
I eventually fixed it by fiddling with the Github authorisation settings. If memory serves, I had to install the Codecov Github app, and give codecov "Third-party application access". Note that this was for an organisation's repository, so some buttons might be named differently for personal ones.
Also, it's been a while since I did this.
