### ISSUE TITLE
Example repos link are using the wrong query parameter to search for repos with example in the name

### ISSUE THREAD

**Issue by metasyn** [codecov/codecov-python#162]
**Version**: Codecov py-v2.0.15 - https://codecov.io/

**Issue:** link does not filter repos

**Expected Behavior:** link does filter repos

**Repro**: run codecov somewhere that fails

I noticed that the link here doesn't work:
```
Tip: See all example repositories: https://github.com/codecov?query=example
Support channels:
  Email:   hello@codecov.io
  IRC:     #codecov
  Gitter:  https://gitter.im/codecov/support
  Twitter: @codecov
```
and it should probably be `q=example` as

https://github.com/codecov?q=example

works.

**Comment by thomasrockhu** [comment]
This has been deprecated, but I appreciate the issue here!
