### ISSUE TITLE
Gitter link does not exist and goes to a 404

### ISSUE THREAD

**Issue by metasyn** [codecov/codecov-python#163]
Version: Codecov py-v2.0.15 - https://codecov.io/

Issue: link does not go to a gitter room

Expected Behavior: link goes to a gitter room

Repro: run codecov somewhere that fails

I noticed that the link here doesn't work:

```

Tip: See all example repositories: https://github.com/codecov?query=example
Support channels:
  Email:   hello@codecov.io
  IRC:     #codecov
  Gitter:  https://gitter.im/codecov/support
  Twitter: @codecov

```

The support room is not listed here:
https://gitter.im/codecov/home

**Comment by thomasrockhu** [comment]
This has been deprecated since to our [community boards](https://community.codecov.io)
