### ISSUE TITLE
allow custom message in codecov report

### ISSUE THREAD

**Issue by szha** [codecov/codecov-python#166]
Hi,

We have a use case where we'd like to add a link to a hosted documentation website for each of our pull request changes when codecov reports. Unfortunately it doesn't seem like an option yet https://docs.codecov.io/docs/pull-request-comments

Questions:
1. is there any easy, unadvertised way for us to inject such custom comment in the report?
2. is this something codecov can support? is there any plan to support it?

Thanks.

**Comment by thomasrockhu** [comment]
Hi @szha, unfortunately, there isn't a way to do this, and the team is unlikely to support this in the near future. I will, however, let the product team know about this.
