### ISSUE TITLE
Codecov not posting coverage report on pull requests

### ISSUE THREAD

**Issue by rahulAirFi** [codecov/codecov-python#180]
I am facing a problem with the feature “codecov will generate a mini code coverage report and post it as a comment to the pull request”, I am getting it for a public repository of mine easily, but, not for a private one. Is there any specific procedure for private repositories? 
Code coverage report for both, public and private, repositories gets uploaded successfully on CodeCov, no issues there.

**Comment by thomasrockhu** [comment]
@rahulAirFi for private repositories, you will need to enable the team bot in order for `Codecov` to be able to write comments.  You can find the documentation here: https://docs.codecov.io/docs/team-bot

**Comment by s1mrankaur** [comment]
@thomasrockhu  Same issue. Team bot is my username in bitbucket but no pull request comments are being generated. We also cannot find any pull requests in the pull requests tab
