### ISSUE TITLE
Wrong mercurial commit regex on drone.io

### ISSUE THREAD

**Issue by saaj** [codecov/codecov-python#19]
Here's response:
```
{"uploaded": false, "meta": {"status": 400, "request": "c2a4534d-2988-4170-9e5c-e454c0cc4a0d"}, "message": "Invalid value '4083:e8ca1b43e114' (str): must match pattern ^\\w{40}
```

**Comment by stevepeak** [comment]
I have not looked into mercurial repos. Perhaps as far as codecov is concerned the only difference from git would be the commit sha. Is this correct? I can fix this up very soon. Thanks making notice of this

**Comment by saaj** [comment]
In mercurial default changeset identifier looks like '4083:e8ca1b43e114'. drone.io probably provides normal mercurial changeset identifier in DRONE_COMMIT. If the endpoint expects full hash, the format can be [customized](http://hgbook.red-bean.com/read/customizing-the-output-of-mercurial.html).

**Comment by stevepeak** [comment]
I'll update our validation schema to allow more characters in the commit sha. How does this change look?

```diff
- /\w{40}/
+ /[\w\:\-\,\.\#]{5,20}/
```

**Comment by saaj** [comment]
Is this Mercurial-specific changeset regex? Why 5 and 20? Okay, 20 means 7 chars left to numeric revision, which is less than 10 million, which is fine. But what is 5? Also this doesn't enforce beginning and end of the match.

**Comment by stevepeak** [comment]
I'm attempting to make a charset for both git and mercurial. Git is easy `\w{40}` what about mercurial? Does my idea work above? (sorry it not 20, its 40, typo)

**Comment by saaj** [comment]
How about `^\d+:\w{12}|\w{40}$`?

**Comment by stevepeak** [comment]
Great, does this satisfy the customization that may occur?

**Comment by saaj** [comment]
It matches Mercurial short changeset id and full hex SHA-1. Double check at http://regex101.com/

**Comment by stevepeak** [comment]
Thanks! I'll make these changes now

**Comment by saaj** [comment]
Now the client's output seems correct:
```
Uploaded: True
Report URL: http://codecov.io/bitbucket/saaj/cherrypy?ref=4094%3A18e3f7c08f04
Upload Version: codecov-v1.1.6
Message: Coverage reports upload successfully
```
But the website still shows "No reports submitted".

**Comment by stevepeak** [comment]
Can you submit another report for me. I did not properly update our production database to allow this commit sha. Thank you!
