### ISSUE TITLE
File loses coverage even though it is not effected by changes

### ISSUE THREAD

**Issue by dtracers** [codecov/codecov-python#199]
https://github.com/SaltieRL/DistributedReplays/pull/270

Randomly some bit of code decided to stop being covered even though it is not effected or any unit test or coverage that is run.

Any way to prevent this?

**Comment by Sciguymjm** [comment]
Likely due to random ranks generation. That particular line of code only runs when the rank is GC, so it's possible that the previous run randomly picked GC and thus ran the code.

**Comment by thomasrockhu** [comment]
If this is still a problem, please open a ticket in the `support` section of our [community boards](https://community.codecov.io).
