### ISSUE TITLE
False positive report upload

### ISSUE THREAD

**Issue by saaj** [codecov/codecov-python#20]
The client outputs:
```
Uploaded: True
Report URL: http://codecov.io/bitbucket/saaj/cherrypy?ref=4094%3A18e3f7c08f04
Upload Version: codecov-v1.1.6
Message: Coverage reports upload successfully
```
But it doesn't appear on the website. Originated from #19.

**Comment by stevepeak** [comment]
Could you submit a new report, I believe I've fixed this. Thanks @saaj

**Comment by saaj** [comment]
I thought you asked me to submit a separate bug report for a bookkeeping concern in #19, not to submit a coverage report ;-) I have just run the build, and the coverage report has reached the website. Thanks.

**Comment by stevepeak** [comment]
No problem :) thanks and let me know if there is anything else I can help with.
