### ISSUE TITLE
Unable to see covered lines

### ISSUE THREAD

**Issue by chfw** [codecov/codecov-python#207]
Hi all

I am having difficult to see which lines are covered and which are not. Here is the link:

https://codecov.io/gh/moremoban/moban/src/5a8281a2ca76ff59642bc7ea4eb6df75819b9bfe/moban/plugins/template.py

How do I see the covered lines in a file on a branch?

Thanks

**Comment by thomasrockhu** [comment]
@chfw going to close this as it's been over a year, and I see coverage on the latest commits. Let me know if this is wrong.
