### ISSUE TITLE
threshold stopped working

### ISSUE THREAD

**Issue by evandrocoan** [codecov/codecov-python#211]
I have set https://github.com/evandrocoan/debugtools/blob/master/codecov.yml the threshold to 2% quite some time, but today, my repo had a change of 0.03 and it triggered as error:

![image](https://user-images.githubusercontent.com/5332158/65822460-bd08ac00-e21a-11e9-943b-d329bc97b5d3.png)

**Comment by thomasrockhu** [comment]
@evandrocoan this is because the yaml is no longer valid. You can re-validate, but I think to fix this situation, just change `target` to

```target: false```
