### ISSUE TITLE
Travis Mac InsecurePlatformWarning

### ISSUE THREAD

**Issue by chillpop** [codecov/codecov-python#22]
I'm using the script to upload coverage reports from Travis on their Mac VM images for iOS development.  Recently, I started seeing the following warning message:
```
/Library/Python/2.7/site-packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```
I'm not specifying what version of python to use in the `.travis.yml` file.
Is this something to be fixed on your end?  Or is it a Travis configuration issue?

**Comment by stevepeak** [comment]
> Reference [SSL InsecurePlatform error when using Requests package](http://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package)

Looks like it is an issue with the `requests` package. In your case, were the reports not uploaded? I'll look into solutions for `python < 2.7.9` which is affected by this issue.

Thanks for reporting!

**Comment by chillpop** [comment]
The reports **do** upload successfully.

**Comment by stevepeak** [comment]
Thats good news :) I'll checkout if I can fix the issue, but meanwhile I'm happy its working.

I'll be creating a `shell` script that does the same uploading behavior so customers do not need to `sudo pip...` Thanks!

**Comment by stevepeak** [comment]
@chillpop the Bash Global Uploader is complete at https://github.com/codecov/codecov-bash it will soon become the featured uploader for Codecov. Thanks!

```yml
sudo: false # (optional) for faster builds
after_success:
  - bash <(curl -s https://codecov.io/bash)
```
