### ISSUE TITLE
Marking comments as uncovered

### ISSUE THREAD

**Issue by rmjarvis** [codecov/codecov-python#227]
Codecov has recently started marking some comment lines as being uncovered.  Most commonly right at the start in my copyright notice.

Here is an example: https://codecov.io/gh/rmjarvis/TreeCorr/src/jk2/treecorr/binnedcorr3.py
9 of the first 12 lines (all of which are comments) are pink, and everything below that is either green or white.  So the file is marked as having only 96% coverage, rather than 100%.

This seems to have started only in the last few months, and I don't think I changed any of my codecov or .coveragerc settings.  But maybe there is something I need to do to one or both of these to tell it to ignore all comment lines?  Or is it possibly a bug on your end (I humbly suggest...)?

Thanks for any help you can provide about this!

**Comment by thomasrockhu** [comment]
Hi @rmjarvis, this looks to be resolved. Let me know if I'm wrong here.

**Comment by rmjarvis** [comment]
Yes.  Thanks, I haven't seen it in quite a while now.
