### ISSUE TITLE
Broken license detection on PyPI

### ISSUE THREAD

**Issue by Paebbels** [codecov/codecov-python#228]
Line 29 in `setup.py` breaks license detection on PyPI.

    license='http://www.apache.org/licenses/LICENSE-2.0',

Source: https://github.com/codecov/codecov-python/blob/master/setup.py?ts=2#L29

The license got already specified via `classifiers`. Moreover, the parameter `license` seems to be outdated. It's not documented in the latest Python documentation.

License detection from PyPI is used by other services like [Shields.io](https://shields.io).  
Here is the (broken) result of codecov: ![](https://img.shields.io/pypi/l/codecov)

The correct output would look like this: ![](https://img.shields.io/pypi/l/pyAttributes)

**Comment by thomasrockhu** [comment]
@Paebbels, I'm not quite sure why this is an issue as the license is `Apache 2.0`. Is this still a problem?

**Comment by Paebbels** [comment]
Because you fixed it meanwhile. The issue was now 8 months old ...
