### ISSUE TITLE
Custom ignored_report

### ISSUE THREAD

**Issue by pcorpet** [codecov/codecov-python#230]
I have a file in my repo that codecov mistakes for a coverage report. Would it be possible to add a flag to this script to ignore reports through a custom regexp?

If you're OK with the idea, I can send a PR.

**Comment by thomasrockhu** [comment]
@pcorpet is this causing issues with the coverage shown by Codecov? It shouldn't be a problem, as we will just not parse it if it's not a valid coverage format.

**Comment by pcorpet** [comment]
Sorry this is old, I don't remember what was the issue. I ended up specfiying the file manually.

However it seems weird that you maintain such a long regexp for ignored_report if it' not an issue.
