### ISSUE TITLE
Codecov v2.0.20 fails in Alpine Linux

### ISSUE THREAD

**Issue by agboom** [codecov/codecov-python#243]
After upgrading from 2.0.15 to 2.0.20 the codecov command fails with the following error:

```
Executing gcov (['find', '/project', "-not -path './bower_components/**' -not -path './node_modules/**' -not -path './vendor/**'", '-type', 'f', '-name', '*.gcno', '', '-exec', 'gcov', '-pb', '', '{}', '+'])
find: unrecognized: -not -path './bower_components/**' -not -path './node_modules/**' -not -path './vendor/**'
```

After that it prints the usage of find:

```
BusyBox v1.31.1 () multi-call binary.
Usage: find [-HL] [PATH]... [OPTIONS] [ACTIONS]
```

Where `BusyBox` is probably a clue to the problem. Codecov probably expects GNU find?

**Comment by agboom** [comment]
The related line in the Codecov script seems to be here: https://github.com/codecov/codecov-python/blob/master/codecov/__init__.py#L689

**Comment by agboom** [comment]
Installing findutils with `apk add findutils` did not fix the issue, but did result in a slightly different error message.

```
find: unknown predicate `-not -path './bower_components/**' -not -path './node_modules/**' -not -path './vendor/**''
    Error running `['find', '/project', "-not -path './bower_components/**' -not -path './node_modules/**' -not -path './vendor/**'", '-type', 'f', '-name', '*.gcno', '', '-exec', 'gcov', '-pb', '', '{}', '+']`: Command '['find', '/project', "-not -path './bower_components/**' -not -path './node_modules/**' -not -path './vendor/**'", '-type', 'f', '-name', '*.gcno', '', '-exec', 'gcov', '-pb', '', '{}', '+']' returned non-zero exit status 1
```

The usage of find was not printed after this.

**Comment by agboom** [comment]
After closer inspection, the regression seems to be introduced in 2.0.17. This coincides with the source code where `find` is used.

**Comment by thomasrockhu** [comment]
`find` has since been removed post `2.1.3` @agboom. Is this still an issue?

**Comment by agboom** [comment]
@thomasrockhu It works again, thanks!
