### ISSUE TITLE
HTTP 400 Invalid signature

### ISSUE THREAD

**Issue by fepegar** [codecov/codecov-python#245]
Hi,

I'd like Codecov to automatically check my code when pushing and when opening a PR. The webhook on GitHub is not working. In https://github.com/fepegar/torchio/settings/hooks/ I can see a lot of failed deliveries such as `b1c1e4ba-7289-11ea-8933-1deeb855d87b`. The body of the response is always `HTTP 400 Invalid signature`. I assume you need more information, please let me know how I can help.

**Comment by thomasrockhu** [comment]
Hi @fepegar, can you open a ticket in the `support` section of our [community boards](https://community.codecov.io)?
