### ISSUE TITLE
Codecov 2.0.22 doesn't find any reports

### ISSUE THREAD

**Issue by Axel13fr** [codecov/codecov-python#249]
To make coverage reports work on my repo, https://github.com/Axel13fr/lib_sonarcov I had to use a fixed revision of codecov back to 2.0.15.

When using 2.0.15 it does find reports and everything works.
https://travis-ci.org/github/Axel13fr/lib_sonarcov/jobs/676087196#L4161
When using 2.0.22 it doesn't find any reports (I haven't tried all the intermediate versions though).
https://travis-ci.org/github/Axel13fr/lib_sonarcov/jobs/676088100#L4113

**Comment by sineverba** [comment]
I can confirm that 2.0.15 works. Related to https://github.com/codecov/codecov-python/issues/247

**Comment by youtux** [comment]
Same problem with pull requests for pytest-bdd:
https://travis-ci.org/github/pytest-dev/pytest-bdd/jobs/677569102

**Comment by thomasrockhu** [comment]
This has been fixed post `2.1.3`
