### ISSUE TITLE
Codecov prints exception traceback when no token is supplied, even though exit status is 0

### ISSUE THREAD

**Issue by joaopimentel** [codecov/codecov-python#26]
Calling codecov without a token results in traceback and error messages.
Returning with 0 is OK, since I may not want a build to fail if I do not intend to send the report to codecov. However, in that case, I'd prefer not to have such an error be displayed:

```
Uploaded: False
Report URL: n/a
Upload Version: codecov-v1.1.8
Message: missing token or other required argument(s)
WARNING:rollbar:Got unexpected status code from Rollbar api: 403
Response:
{
  "err": 1,
  "message": "access token not found: 856822f107db4a6a8cd84b69e242378f"
}
ERROR:rollbar:Exception while posting item ApiError(u'access token not found: 856822f107db4a6a8cd84b69e242378f',)
Traceback (most recent call last):
    (...traceback...)    
    raise ApiError(json_data.get('message') or 'Unknown error')
ApiError: access token not found: 856822f107db4a6a8cd84b69e242378f
```
I think a basic "token not provided, report not uploaded" message could be more helpful :wink:

**Comment by stevepeak** [comment]
The access token issue was due to my Rollbar reporting. Thats fixed and released just now, just forgot to deploy that fix.

Thanks! For posting this issue ;)
