### ISSUE TITLE
AppVeyor still requires token.

### ISSUE THREAD

**Issue by Robpol86** [codecov/codecov-python#27]
I got an email a few weeks ago that said "Integration Using Appveyor CI? You no longer need a repo token for public repos.".

However I'm getting this traceback:
```
Traceback (most recent call last):
  File "C:\Python34-x64\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34-x64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34-x64\Scripts\codecov.exe\__main__.py", line 9, in <module>
  File "C:\Python34-x64\lib\site-packages\codecov\__init__.py", line 285, in cli
    data, codecov = main()
  File "C:\Python34-x64\lib\site-packages\codecov\__init__.py", line 278, in main
    data = upload(url=codecov.url, branch=codecov.branch, commit=codecov.commit, token=codecov.token, env=codecov.env, slug=codecov.slug, **defaults)
  File "C:\Python34-x64\lib\site-packages\codecov\__init__.py", line 120, in upload
    result.raise_for_status()
  File "C:\Python34-x64\lib\site-packages\requests\models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request
{"message": "token or build not found", "meta": {"request": "22e2fb93-cad4-485b-8960-bffaacc5ddaf", "status": 400}, "uploaded": false}
```

https://ci.appveyor.com/project/Robpol86/terminaltables/build/1.0.152
https://github.com/Robpol86/terminaltables/tree/1a8e68f10accf7e8097cec9dd52af3befc47b97f

appveyor.yml:
```yaml
init:
  - set PATH=C:\Python34-x64;C:\Python34-x64\Scripts;%PATH%
install:
  - ps: Start-FileDownload https://raw.github.com/pypa/pip/master/contrib/get-pip.py
  - python get-pip.py
build_script:
  - pip install codecov tox
test_script:
  - tox
  - tox -e combine py34x64 py34 py33x64 py33 py27x64 py27
after_test:
  - mv tests/.coverage .
  - codecov
```

**Comment by jayvdb** [comment]
I also experienced this with Python; maybe the Python library needs updating.  The workaround is to put the token in CODECOV_TOKEN

**Comment by stevepeak** [comment]
Could we try another build. I patched an issue that I found earlier and would like to try this integration again. Thank you for your patience :)

**Comment by jayvdb** [comment]
No worries. No rush here. Do you need me to do anything?

**Comment by stevepeak** [comment]
Thanks! Could you push a commit through with no repo token :) Send me the build url to so I can double check it all.

**Comment by jayvdb** [comment]
Here is a build with no token in the env vars:
https://ci.appveyor.com/project/jayvdb/python-appveyor-demo

If it is successful, I'll redo my PR tomorrow so that the appveyor.yml doesnt check the env var.  I'm hitting the hay for today.

**Comment by stevepeak** [comment]
The first build looks good: http://codecov.io/github/jayvdb/python-appveyor-demo?ref=99d4f47ab1de6d6d3ab2ea6a8cbbfd4d3d1887ef

I'm happy this is working again. The issue was the report json from AppVeyor sometimes did't include data I was expecting. Fixed that up :+1:
