### ISSUE TITLE
Need to enable codecov on PR Level as GitHub Actions for Checks

### ISSUE THREAD

**Issue by fahadshehzada** [codecov/codecov-python#281]
I'm using codecov.io 

Run codecov/codecov-action@v1.0.7
with:
token: ***
file: services/billing/src/coverage/clover.xml
flags: billing
/bin/bash codecov.sh -f services/billing/src/coverage/clover.xml -n -F billing

![image](https://user-images.githubusercontent.com/61680750/84704462-4d3a7d00-af73-11ea-9bd0-50ae83285e03.png)

Running above GitHub action, generating report as well but not showing on checks with code coverage stats. I need code coverage as checks on PR level

![image](https://user-images.githubusercontent.com/61680750/84704502-5e838980-af73-11ea-8c2c-c9daf7dc046f.png)

**Comment by thomasrockhu** [comment]
Hi @fahadshehzada, are you looking for [status checks](https://docs.codecov.io/docs/commit-status)?

**Comment by fahadshehzada** [comment]
> Hi @fahadshehzada, are you looking for [status checks](https://docs.codecov.io/docs/commit-status)?

Yes
