### ISSUE TITLE
Unable to get Codecov badge for a specific release or tag

### ISSUE THREAD

**Issue by syncrostone** [codecov/codecov-python#283]
I would like to use a release-specific Codecov badge for a stable release in documentation. I have [made and tagged the release in github](https://github.com/murraylab/PsychRNN/releases/tag/v0.4). Is there a way to get a codecov badge for a release tag? If not, it would be great if that feature could be added.

With Travis.ci, tests automatically run for the tag / release, and I can use that badge, e.g.  using the link [https://api.travis-ci.com/murraylab/PsychRNN.svg?branch=v0.4](https://api.travis-ci.com/murraylab/PsychRNN.svg?branch=v0.4). Codecov does not currently run coverage checks for tags as far as I can tell, and so I can't figure out how to get a codecov badge for my release tag -- https://codecov.io/gh/murraylab/PsychRNN/branch/0.4/graph/badge.svg and https://codecov.io/gh/murraylab/PsychRNN/branch/v0.4/graph/badge.svg both fail.

**Comment by thomasrockhu** [comment]
Hi @syncrostone, this is a great feature request. Do you mind opening something in the `feature-request` section of our [community boards](https://community.codecov.io)?

**Comment by syncrostone** [comment]
I've opened a [request on the community board](https://community.codecov.io/t/release-specific-codecov-badge/2273).
