### ISSUE TITLE
Coverage reports are uploaded for the wrong GitHub project

### ISSUE THREAD

**Issue by exarkun** [codecov/codecov-python#309]
This is a problem I've observed on coverage reports for PRs for https://github.com/tahoe-lafs/tahoe-lafs.  A PR which demonstrates this problem can currently be found at https://github.com/tahoe-lafs/tahoe-lafs/pull/926.

The symptom of this problem is that codecov believes some amount of coverage is missing.  The reality is that the missing coverage is in reports that have been uploaded and associated with the wrong project.  In example case, the reports should be associated with tahoe-lafs/tahoe-lafs but instead they have been associated with sajith/tahoe-lafs.

The configuration can be summarized thusly:

* tahoe-lafs/tahoe-lafs uses CircleCI for some of its CI
* tahoe-lafs/tahoe-lafs uses codecov-python to report coverage to codecov
* tahoe-lafs/tahoe-lafs has a `.codecov.yaml` but does not use it to supply a codecov repository upload token

Coverage information collected from GitHub Actions can be see in the right place: https://codecov.io/gh/tahoe-lafs/tahoe-lafs/commit/b787de0acc6c1b9d1491a54539bf3ed458732a19/build

But the coverage information collected from CircleCI can only be seen in the wrong place: https://codecov.io/gh/sajith/tahoe-lafs/commit/b787de0acc6c1b9d1491a54539bf3ed458732a19/build

**Comment by thomasrockhu** [comment]
@exarkun, can you open a ticket on our [community boards](https://community.codecov.io) for this?

**Comment by exarkun** [comment]
I don't see a compelling reason to do that.
