### ISSUE TITLE
tool does not respect fixes

### ISSUE THREAD

**Issue by williamcroberts** [codecov/codecov-python#318]
As far as I can tell the tool does not respect the fixes in the codecov.yml file. Theirs no reference to the fixes key in the YAML file in the code, and seems to not be doing anything locally. I walked through it with a debugger and don't see any spot where it does that.

**Comment by thomasrockhu** [comment]
@williamcroberts can you open a ticket in our [community boards](https://community.codecov.io), so I can dig into what might be happening?

**Comment by williamcroberts** [comment]
Done:
  - https://community.codecov.io/t/codecov-python-does-not-respect-fixes-in-codecov-yml-file/2768

I dunno what moving it over there does, likely just moved it into a black hole.

**Comment by thomasrockhu** [comment]
@williamcroberts yikes, I'm that black hole.  I updated on the ticket, but could you provide a commit SHA or this happening?

**Comment by williamcroberts** [comment]
> @williamcroberts yikes, I'm that black hole. I updated on the ticket, but could you provide a commit SHA of this happening?

I ran all the tools locally, so I could debug them. Can you point to a test in the bash-uploader or python scripts where the"path-fix"  feature is tested? I can't find any reference to it.

**Comment by williamcroberts** [comment]
I'm using the master tip of codecov python and bash tools.  Various uploads to the tpm2-pytss project failed, so I replicated everythign locally to debug, which is when I discovered the paths not lining up and trying to do a path fix.  If you just look at the python tool:
  - https://github.com/codecov/codecov-python/blob/master/codecov/__init__.py

You should see a regex grabbing the fixes field and applying a fixup to the code paths in the coverage report. I have some changes locally to codecov-python to implement this, but its not will tested.

**Comment by thomasrockhu** [comment]
@williamcroberts `path fixing` is handled server-side. I asked for a commit SHA so I could see what was happening for your particular case.

**Comment by williamcroberts** [comment]
> @williamcroberts `path fixing` is handled server-side. I asked for a commit SHA so I could see what was happening for your particular case.

That explains that. I unfortunately force-pushed. But I can get a branch and revert the change and redo it so we can get some debugging. Is their anyway to introspect what the server is doing?

**Comment by williamcroberts** [comment]
@thomasrockhu I created a branch with the older method that was failing, ill post back with details when it's done:
  - https://github.com/tpm2-software/tpm2-pytss/actions/runs/764010764

**Comment by thomasrockhu** [comment]
> Is their anyway to introspect what the server is doing?
Unfortunately not in a public way. I'll make a note to the product team to make this process easier and more self-servicing for users, though.

**Comment by williamcroberts** [comment]
@thomasrockhu thanks again for spending cycles looking at this:

Here is the CI side upload, I added a --dump before the upload so we could see the data:
 - https://github.com/tpm2-software/tpm2-pytss/runs/2382176442?check_suite_focus=true#step:6:615

Upload link to codecov shows "There was an error processing coverage reports":
  - https://codecov.io/github/tpm2-software/tpm2-pytss/commit/1c0f16478c6bc29fc3b803b5430426261ca67249

Do you spot what the issue is? I can do a dump on the fully working one so we have a diff.

**Comment by thomasrockhu** [comment]
@williamcroberts I see that the coverage file uploaded to Codecov is [empty](https://github.com/tpm2-software/tpm2-pytss/runs/2382176442?check_suite_focus=true#step:6:686) which is why you probably got that error.

**Comment by williamcroberts** [comment]
> @williamcroberts I see that the coverage file uploaded to Codecov is [empty](https://github.com/tpm2-software/tpm2-pytss/runs/2382176442?check_suite_focus=true#step:6:686) which is why you probably got that error.

Do you know why, or what to poke at, when it is empty? I don't understand why coverage is reporting above and the .coverage sqlite3 db had coverage data.
