### ISSUE TITLE
gitlab-ci-multi-runner `codecov` does not find coverage.xml

### ISSUE THREAD

**Issue by raabf** [codecov/codecov-python#33]
I try to get `codecov` working on my gitlab-ci.
As runner/slave is use [gitlab-ci-multi-runner](https://gitlab.com/gitlab-org/gitlab-ci-multi-runner) in `shell` mode, therefore simply using the local shell.

The error message `codecov` prints:

```
No reports found. You may need to add a coverage config file. Visit http://bit.ly/1slucpy for configuration help.Uploaded: False
Report URL: n/a
Upload Version: codecov-v1.1.9
Message: error no coverage report found, could not upload to codecov
```

Do data is uploaded in reality.

You can see the an example build [here](https://ci.gitlab.com/projects/3804/builds/94826)

I also execute `ls -la` and like you see the `coverage.xml` exists and has a file size. All other commands run well with the runner. The runner run all commands in the same directory like usual.

I can type in exactly the same commands on the same machine (where the runner is executed) with the same user (`gitlab_ci_multi_runner`) and everything works well, but not automatically via the CI.

I have no ideas left. Suggestions?

EDIT: Like you see with `ls -la` the *coverage config* also exists ...

**Comment by stevepeak** [comment]
This is indeed strange behavior. Could you try out other uploader and send me the results. Thanks!

```diff
- codecov --token=0fd4bb3c-9610-496b-b43f-fc1de2c0b07f
+ bash <(curl -s https://codecov.io/bash) -t 0fd4bb3c-9610-496b-b43f-fc1de2c0b07f
```

**Comment by raabf** [comment]
He seems to cd into the false directory (codecov seems to assume that the actual dir is the home dir of the user)?

[complete run](https://ci.gitlab.com/projects/3804/builds/95797)

```shell
pwd
/home/gitlab_ci_multi_runner/tmp/builds/runner-40962cab-project-3804-concurrent-0/gitlab.com/bgp-comm-db/bgp-comm-db-framework
bash <(curl -s https://codecov.io/bash) -t 0fd4bb3c-9610-496b-b43f-fc1de2c0b07f
curl -s https://codecov.io/bash
Codecov v0.0.6
(url) https://codecov.io
GitLab CI detected.
/dev/fd/63: line 305: cd: tmp/builds/runner-40962cab-project-3804-concurrent-0/gitlab.com/bgp-comm-db/bgp-comm-db-framework: No such file or directory

Build failed with exit status 1
```

**Comment by stevepeak** [comment]
The Bash script will `cd` in to the `$CI_PROJECT_DIR ` [here](https://github.com/codecov/codecov-bash/blob/abe23f698a16e9ff8fd321c294634e4651dd93e1/codecov#L305). Perhaps this is whats causing issues.

Lets try this uploader with fixes.

```sh
bash <(curl -x https://raw.githubusercontent.com/codecov/codecov-bash/master/codecov) -t 0fd4bb3c-9610-496b-b43f-fc1de2c0b07f
```

Thanks!

**Comment by raabf** [comment]
Looks good :smile:

[CI page](https://ci.gitlab.com/projects/3804/builds/99425)

**Comment by stevepeak** [comment]
Great news! I'll be deploying these fixes shortly. Thank you for your help and patience!!

**Comment by stevepeak** [comment]
@raabf hey :) Checking back on this issue. Noticed in one of your latest build the Upload token is missing: https://ci.gitlab.com/projects/3804/builds/125606

As for the error above that its related to https://github.com/codecov/support/issues/43. Which will depreciate when `coveragepy v4.0` is released [fixing this issue via this commit](https://bitbucket.org/ned/coveragepy/commits/b286ca8a2938)

Cheers!
