### ISSUE TITLE
`coverage xml` failures are not detailed

### ISSUE THREAD

**Issue by ionelmc** [codecov/codecov-python#36]
I got a failure here https://travis-ci.org/ionelmc/pytest-benchmark/jobs/75152592#L284 like this:

```
/home/travis/build/ionelmc/pytest-benchmark$ /home/travis/build/ionelmc/pytest-benchmark/.tox/codecov/bin/codecov 

Error running `coverage xml`. Codecov team will be notifiedNo reports found. You may need to add a coverage config file. Visit http://bit.ly/1slucpy for configuration help.Uploaded: False

Report URL: n/a

Upload Version: codecov-v1.2.3

Message: error no coverage report found, could not upload to codecov
```

I would be nice to get the complete output of `coverage xml`.

**Comment by stevepeak** [comment]
I believe this next update will suffice: #34 via https://github.com/codecov/codecov-python/blob/73b5a2efdd2ba7af1614115eccdce179a0333f5b/codecov/__init__.py#L178-L182

Thoughts?

**Comment by ionelmc** [comment]
That should do the trick. Thanks.
