### ISSUE TITLE
Not showing lines covered when used by multiprocessing.Process

### ISSUE THREAD

**Issue by gappleto97** [codecov/codecov-python#47]
This results in large portions of code showing up as uncovered, despite being covered.

[Example](https://codecov.io/github/gappleto97/Senior-Project/common/peers.py?ref=24db3f7116e0c8c0373a40cb14b74f27f630d156#line-115)

**Comment by stevepeak** [comment]
This issue is likely due to `coveragepy` project. Are you able to run coverage locally and get the correct expected results? Codecov only processes the reports and is not responsible to gathering the coverage data. Thank you!
