### ISSUE TITLE
Support for Buildkite

### ISSUE THREAD

**Issue by bforchhammer** [codecov/codecov-python#53]
Hey,

I'd love to see support for buildkite. They expose all the necessary env variables as far as I can see, so integration should be relatively straight-forward: https://buildkite.com/docs/guides/environment-variables

Some things I can set by passing them as arguments to the command, but things like the "pr" parameter are not exposed at the moment, as far as I can see :-)

Thanks!

**Comment by stevepeak** [comment]
Hey @bforchhammer thanks for submitting this issue. We do support Buildkite in our [bash uploader](https://github.com/codecov/codecov-bash). I'll add it into the Python one as well. Thanks!

**Comment by bforchhammer** [comment]
Thanks for your reply. The bash uploader is working very well for us.

Is there any reason for preferring the python version instead of the bash uploader? I only started with this one because it seemed to be the recommended way of setting if up after setting up a new project on codecov, but the bash uploader seems to do the job just as well and does not require installing an extra dependency.

**Comment by stevepeak** [comment]
@bforchhammer The bash and python uploader are essentially the same, however the xcode requires the Bash uploader (currently).

To be honest the preference between the two is mealy personal. We typically push the Bash uploader because of its simplicity. All three global uploading utils (bash, python, node) will continue to get the most attention and will always remain up-to-date.

**Comment by bforchhammer** [comment]
Cool, thanks!

Maybe the "Setup Guides" section when you set up a new repository on codecov.io coiuld be updated to point to all upload variants; for python projects it currently only points me to the python uploader, the bash uploader isn't mentioned.

**Comment by thomasrockhu** [comment]
This should be solved here: https://github.com/codecov/codecov-python/blob/master/codecov/__init__.py#L573
