### ISSUE TITLE
project path is wrong if building with gitlab ci runner

### ISSUE THREAD

**Issue by fckw** [codecov/codecov-python#54]
Hi,

the path used for searching the report data is incorrect if building the project with a gitlab ci runner.

gitlab-ci-multi-runner provides a absolute path for the project directory. It was introduced by [this commit ](https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/commit/0e50a4334aa0bb162e3e0c845401a369ae9841b0) and included in v0.7.

So it would be nice if you could revert the change introduced in your commit [564bc23f1542dd...](https://github.com/codecov/codecov-python/commit/564bc23f1542dd9de36e11b5867401e4c7a03769)

Thanks and regards
Philip

**Comment by pvorb** [comment]
I can confirm this behavior. This is what happens on GitLab CI Multi Runner when I run `codecov`:

~~~
codecov --token=$codecov_upload_token
/bin/sh: 1: cd: can't cd to /root//builds/pvorb/gitlab-ci-java-gradle-codecov
find: `/root//builds/pvorb/gitlab-ci-java-gradle-codecov': No such file or directory

      _____          _
     / ____|        | |
    | |     ___   __| | ___  ___ _____   __
    | |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
    | |___| (_) | (_| |  __/ (_| (_) \ V /
     \_____\___/ \__,_|\___|\___\___/ \_/
                                    v1.6.3

==> Detecting CI provider
    Gitlab CI Detected
==> Preparing upload
    Error running `cd /root//builds/pvorb/gitlab-ci-java-gradle-codecov && git ls-files`: 
==> Processing gcov (disable by -X gcov)
    Executing gcov (find /root//builds/pvorb/gitlab-ci-java-gradle-codecov -type f -name '*.gcno'  -exec gcov -pb  {} +)
    Error running `find /root//builds/pvorb/gitlab-ci-java-gradle-codecov -type f -name '*.gcno'  -exec gcov -pb  {} +`: 
==> Collecting reports
Error: No coverage report found
~~~

In this case, the following environment variables are set:

~~~
HOME=/root
CI_PROJECT_DIR=/builds/pvorb/gitlab-ci-java-gradle-codecov
~~~
