### ISSUE TITLE
'ascii' codec can't encode characters in position...

### ISSUE THREAD

**Issue by bbalet** [codecov/codecov-python#56]
I get an error while trying to use the uploader for a Go project:
https://github.com/bbalet/stopwords

    'ascii' codec can't encode characters in position 13398-13493: ordinal not in range(128)

Apparently, this is a known issue with Python, see:

- http://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20
- http://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20

Attached is the log generated by Travis-CI where you can find this error:
[log.txt](https://github.com/codecov/codecov-python/files/124394/log.txt)

**Comment by fckw** [comment]
Commit [4525409ddc5a...](https://github.com/codecov/codecov-python/commit/4525409ddc5a3f0194848a795262e6785acbaa37) should fix the problem (partially).

Additionally I had to perform a string cast of "reports" in codecov/__init__.py:621 and codecov/__init__.py:665.

The report upload seems to work now. Nevertheless, the coverage is not displayed in the gitlab enterprise web app and the following error can be found in the logs:

`[2016-02-03 16:06:20,080: INFO/Worker-1] {"build": null, "commit":
"f73598f", "func": "upload", "processing": true, "reportid":
"upload:242:f73598fe7a0dd72c0300c062d403a60e160f32d0:na:6827:1454511969.88",
"service": "gitlab_enterprise", "slug": "libs/encoding", "trys": 0}
{"service": "gitlab_enterprise", "traceback": ["Traceback (most recent
call last):\n", "  File \"/home/ubuntu/codecov.io/app/tasks/upload.py\",
line 544, in upload\n", "Exception: Report not found in redis.\n"],
"trys": 0, "build": null, "func": "upload", "action": "error", "commit":
"f73598f", "slug": "libs/encoding", "reportid":
"upload:242:f73598fe7a0dd72c0300c062d403a60e160f32d0:na:6827:1454511969.88"}
[2016-02-03 16:06:20,082: ERROR/Worker-1] {"service":
"gitlab_enterprise", "traceback": ["Traceback (most recent call
last):\n", "  File \"/home/ubuntu/codecov.io/app/tasks/upload.py\", line
544, in upload\n", "Exception: Report not found in redis.\n"], "trys":
0, "build": null, "func": "upload", "action": "error", "commit":
"f73598f", "slug": "libs/encoding", "reportid":
"upload:242:f73598fe7a0dd72c0300c062d403a60e160f32d0:na:6827:1454511969.88"}`

**Comment by stevepeak** [comment]
Deploying shortly via `v1.6.5`. Thank you!

**Comment by stevepeak** [comment]
@fckw your error will be resolved via `v.1.6.5
