### ISSUE TITLE
Codecov.io returns 400 for AppVeyor builds with spaces.

### ISSUE THREAD

**Issue by otac0n** [codecov/codecov-python#65]
It seems that spaces need to be encoded as `%20` instead of `+`.

**Comment by otac0n** [comment]
Here's an example build if it helps verify the issue:

https://ci.appveyor.com/project/otac0n/pegasus/build/3.2.0-unstable.130%20(Build%2022)

**Comment by stevepeak** [comment]
Hey @otac0n thanks for pointing this out. I can confirm it it an issue with the spaces. We use the `&job` argument to verify the build with AppVeyor API's.
Thank you!
