### ISSUE TITLE
How does one use --gcov-args?

### ISSUE THREAD

**Issue by ctb** [codecov/codecov-python#67]
Hi all, trying to pass a parameter to gcov with '--gcov-args'.

As far as I can tell, the args.gcov_args is transmitted verbatim to gcov in the find command
(https://github.com/codecov/codecov-python/blob/master/codecov/__init__.py#L567), but argparse won't take any arguments that start with a '-'. I don't find any tests that demonstrate the right way to use it, either. Tips?
thx!

**Comment by stevepeak** [comment]
Can you try this technique, using quotes:

```
codecov --gcov-args="-a -b -c"
```

Thanks!

**Comment by ctb** [comment]
thanks, works perfectly.  Don't know why I didn't think of that... :)
