### ISSUE TITLE
Pull Requests with a '#' in the name cause the coverage report upload to fail

### ISSUE THREAD

**Issue by kavdev** [codecov/codecov-python#69]
example: ``feature/#123_new_feature``. Using CircleCI

**Comment by stevepeak** [comment]
Hey @kavdev thank you for sharing! Can you grab the output from the codecov step in your Circle build. I'm curious at what point it failed. Thank you

**Comment by kavdev** [comment]
@stevepeak: I'd love to, but it seems deleting the branch on github removes the build history for that branch on circleci. If you know how to pull it up, I'd be happy to go find the logs.

It failed while uploading to codecov; I believe the branch parameter came before the commit parameter and the '#' wiped out the rest of the query string. Pretty sure it was a 400 error complaining about the lack of required param ``commit``

**Comment by kavdev** [comment]
(Feel free to close when ready)

**Comment by stevepeak** [comment]
@kavdev are you using the python or bash uploader? I found the issue in the bash but not python uploader. Thanks!

**Comment by kavdev** [comment]
@stevepeak: The bash uploader: ``bash <(curl -s https://codecov.io/bash) -t ****``

**Comment by stevepeak** [comment]
@kavdev fixed ;) thank you!

**Comment by kavdev** [comment]
@stevepeak: I just realized I posted this in the wrong repo. Apologies, but thank you for fixing it.
