### ISSUE TITLE
failed to exec coverage

### ISSUE THREAD

**Issue by jayvdb** [codecov/codecov-python#71]
On Windows, if the Python "Scripts" directory is not in the `PATH`, and codecov is invoked like `C:\...\Scripts\codecov`, `try_to_run` will fail to exec coverage.  The same could happen on Unix, but it is less likely.

This can be avoided a few ways, e.g. by calling coverage as a Python package, adding the "Scripts" directory to the PATH for the exec, using `sys.executable -m coverage` on Python 2.7+, etc.

**Comment by stevepeak** [comment]
Thanks for expressing this issue @jayvdb.

Would you recommend us trying something like:
```
if try_to_run('coverage xml') fails:
  try_to_run('sys.executable -m coverage')
```

**Comment by jayvdb** [comment]
On Py2.7+, then yes, if the failure was that `coverage` was not found.
Rather than trying to work out why `coverage xml` failed, on Python 2.7+ the approach should be to check if coverage exists , then invoke `sys.executable`.

```python
try:
    import coverage
    try_to_run('sys.executable -m coverage xml')
except ImportError:
    try_to_run('coverage xml')
```

Py2.6 has problems with `-m` , and I am not sure that it can be worked around.

However. if you can import and use coverage within Python, rather than creating a subprocess, that would work on Py 2.6, be faster, and give greater control over how `coverage` failures.

**Comment by takluyver** [comment]
#202 is my attempt to fix this.
