### ISSUE TITLE
$CODECOV_ENV documentation URL dead

### ISSUE THREAD

**Issue by peterjc** [codecov/codecov-python#75]
From the help text,

```
$ codecov
...
  --env [ENV [ENV ...]], -e [ENV [ENV ...]]
                        Store environment variables to help distinguish CI
                        builds. Example: http://bit.ly/1ElohCu
...
```

Comes from this line:

``` python
basics.add_argument('--env', '-e', nargs="*", default=os.getenv("CODECOV_ENV"), help="Store environment variables to help distinguish CI builds. Example: http://bit.ly/1ElohCu")
```

Sadly http://bit.ly/1ElohCu resolves to https://codecov.io/github/pyca/cryptography/src/cryptography?ref=db86de59b02be0793dea5e862090586c31998ad1 which gives an Error 404

Note the codecov-bash help text is different:

```
    -e ENV       Specify environment variables to be included with this build
                 ex. codecov -e VAR,VAR2
                 (or) set environment variable CODECOV_ENV=VAR,VAR2
```

**Comment by stevepeak** [comment]
Thanks for pointing this out! I've been working on our [new documentation](https://github.com/codecov/support/wiki) and will be adding documentation for this asap.

Meanwhile, the env is expressed in the builds page on Codecov to help identify the source of the coverage reports. This is typically used for language and system versions. We are looking into ways to add these variables to our UI to help customers refine reports more effectively.

**Comment by peterjc** [comment]
With the recent changes you explicitly *combine* the options given in ``$CODECOV_ENV`` and the command line (``-e`` or ``--env``), which is sensible behaviour.

The help string still needs updating though.

**Comment by stevepeak** [comment]
Done 👍 I'll be adding more docs to this and examples asap
