### ISSUE TITLE
Empty $TRAVIS_PYTHON_NAME included regardless of --env / -e

### ISSUE THREAD

**Issue by peterjc** [codecov/codecov-python#77]
It seems (possibly due to a change on TravisCI), that ``$TRAVIS_PYTHON_NAME`` is currently empty, e.g.

https://codecov.io/gh/ipython/ipython/commit/c17ff28cb1220a91d94fc0dc4b85ccee561fb68f/builds

https://codecov.io/gh/biopython/biopython/commit/2d7619594003460b61fab62260ce50f6a344ba63/builds

Reading the code for ``--env`` aka ``-e``, the current behaviour is to automatically add some additional environment variables over-riding those specified at the command line, e.g. for TravisCI

``` python
include_env.add('TRAVIS_OS_NAME')
include_env.add('TRAVIS_%s_NAME' % language.upper())
include_env.add('TOXENV')
```

and for Snap:

``` python
include_env.add(os.getenv('DISPLAY'))
```

Having these as the default is nice (if ``-env`` or ``-e`` is not used), but to me having them over-ride the command line is surprising. As per #75 the documentation here could be clearer?

**Comment by stevepeak** [comment]
They don't appear to override the cli options. How are you running codecov that you experienced this?

**Comment by peterjc** [comment]
Regarding the blank ``$TRAVIS_PYTHON_NAME`` and how I am running codecov under TravisCI:

The Biopython example https://codecov.io/gh/biopython/biopython/commit/2d7619594003460b61fab62260ce50f6a344ba63/builds shows six TravisCI builds, e.g.

```
2586.9
August 8th 2016, 11:30:03 pm
TOXENV=pypy-cover
TRAVIS_OS_NAME=linux
TRAVIS_PYTHON_NAME=
```

That corresponds to the ``TOXENV=pypycov`` entry in the tox configuration file https://github.com/biopython/biopython/blob/2d7619594003460b61fab62260ce50f6a344ba63/.travis-tox.ini run from TravisCI via https://github.com/biopython/biopython/blob/2d7619594003460b61fab62260ce50f6a344ba63/.travis.yml

Note as per https://github.com/codecov/codecov-python/pull/76 I am passing ``TRAVIS_*`` (which should include ``$TRAVIS_PYTHON_NAME``) to tox, so codecov should have access to it as set by TravisCI.

The second example https://codecov.io/gh/ipython/ipython/commit/c17ff28cb1220a91d94fc0dc4b85ccee561fb68f/builds is not mine. The do have a ``tox.ini`` file https://github.com/ipython/ipython/blob/c17ff28cb1220a91d94fc0dc4b85ccee561fb68f/tox.ini but it is not used under TravisCI: https://github.com/ipython/ipython/blob/c17ff28cb1220a91d94fc0dc4b85ccee561fb68f/.travis.yml

i.e. The blank ``$TRAVIS_PYTHON_NAME`` appears to be stemming from something in these TravisCI Python builds. My guess is we are both using a TravisCI build matrix.

**Comment by peterjc** [comment]
Regarding:

> They don't appear to override the cli options.

The command line is parsed here https://github.com/codecov/codecov-python/blob/master/codecov/__init__.py#L201

``` python
basics.add_argument('--env', '-e', nargs="*", default=os.getenv("CODECOV_ENV"), help="Store environment variables to help distinguish CI builds. Example: http://bit.ly/1ElohCu")
```

Assigned here https://github.com/codecov/codecov-python/blob/master/codecov/__init__.py#L238

``` python
include_env = set(codecov.env or [])
```

At this point ``-e`` or ``-e FOO`` would give ``include_env =set( [])`` or ``include_env = set(['FOO'])``.

Then, on the TravisCI branch this code is called https://github.com/codecov/codecov-python/blob/master/codecov/__init__.py#L286

``` python
            include_env.add('TRAVIS_OS_NAME')
            if language:
                include_env.add('TRAVIS_%s_NAME' % language.upper())

            if language == 'python' and os.getenv('TOXENV'):
                include_env.add('TOXENV')
```

At this point if ``-e`` or ``-e FOO`` was specified rather than ``include_env =set( [])`` or ``include_env = set(['FOO'])``, we get ``include_env = set(['TRAVIS_OS_NAME', 'TRAVIS_PYTHON_NAME', 'TOXENV')])`` or ``include_env = set(['FOO', 'TRAVIS_OS_NAME', 'TRAVIS_PYTHON_NAME', 'TOXENV')])`` (assuming Python).

i.e. The user specified list has been overridden.

**Comment by peterjc** [comment]
OK, the new ``_add_env_if_not_empty`` function makes sense and fixes the main part of this bug.

Separately with the new changes you explicitly *combine* the options given in ``$CODECOV_ENV`` and the command line (``-e`` or ``--env``), which is sensible behaviour although perhaps the help needs to be a little clearer?

Thanks
