### ISSUE TITLE
Build fail in AppVeyor

### ISSUE THREAD

**Issue by joaoasrosa** [codecov/codecov-python#80]
Using the instructions for .NET and Python I've the following error running codecov -f "file":
codecov : File not found - '*.gcno'

For more information: https://ci.appveyor.com/project/joaoasrosa/unittestsexternalsources/build/1.0.51

**Comment by vmuriart** [comment]
Move the [call to codecov](https://github.com/joaoasrosa/unittestsexternalsources/blob/8baf61323e9c3b3528a75939d9bcce8947303155/appveyor.yml#L54) to after test.

From:
```
    pip install git+git://github.com/codecov/codecov-python.git

    codecov -f $resultsFile -X gcov
artifacts:
- path: artifacts\**\*.*
```

To:
```
    pip install git+git://github.com/codecov/codecov-python.git

after_test:
    codecov -f $resultsFile -X gcov
artifacts:
- path: artifacts\**\*.*
```

**Comment by laedit** [comment]
The important part here is the `-X gcov` arg of `codecov` to disable gcov when not needed.

**Comment by thomasrockhu** [comment]
I'm going to close this out due to age, but if this is still a need, please open an issue on our [community boards](https://community.codecov.io)
