### ISSUE TITLE
-e Flag Doesn't Accept Multiple Var Names

### ISSUE THREAD

**Issue by wbond** [codecov/codecov-python#83]
https://github.com/codecov/codecov-python/blob/master/codecov/__init__.py#L246-L249

It should split on `,` like it does at:

https://github.com/codecov/codecov-python/blob/master/codecov/__init__.py#L251-L254

**Comment by wbond** [comment]
Actually, this appears to be an issue that only version 2.0.5 is on PyPI, even though 2.0.6 is released here.

 - https://pypi.python.org/pypi/codecov
 - https://github.com/codecov/codecov-python/releases

**Comment by stevepeak** [comment]
Hey @wbond thank you for pointing this out. I've added support for `-e VAR1,VAR2`. Previous this was the technique: `-e VAR1 -e VAR2`

**Comment by wbond** [comment]
Thanks, much appreciated! I think I did eventually figure out the alternate method, it just took a little digging into how argparse worked.
