### ISSUE TITLE
Cannot upload test results that contain characters outside of latin-1

### ISSUE THREAD

**Issue by JordonPhillips** [codecov/codecov-python#85]
For the past several months (at least 3) codecov has failed to work when test results contain unicode characters. Codecov outputs the following:

```
==> Detecting CI provider
    Travis Detected
==> Preparing upload
==> Processing gcov (disable by -X gcov)
    Executing gcov (find /home/travis/build/boto/botocore -type f -name '*.gcno'  -exec gcov -pb  {} +)
==> Collecting reports
    + /home/travis/build/boto/botocore/tests/nosetests.xml bytes=1746359
    Generating coverage xml reports for Python
    + /home/travis/build/boto/botocore/coverage.xml bytes=262229
==> Appending environment variables
    + TRAVIS_PYTHON_NAME
    + TRAVIS_OS_NAME
==> Uploading
    .url https://codecov.io
    .query [redacted]
    Pinging Codecov...
    Uploading to S3...
Error: 'latin-1' codec can't encode character '\u2713' in position 1651009: Body ('✓') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

Tip: See an example python repo: https://github.com/codecov/example-python
Support channels:
  Email:   hello@codecov.io
  IRC:     #codecov
  Gitter:  https://gitter.im/codecov/support
  Twitter: @codecov
```

I'm unsure why this suddenly stopped working, but it does appear to coincide with the [requests upgrade](https://github.com/codecov/codecov-python/commit/7386c3c13fc71f237611c780646fa1b44a07dc64#diff-2eeaed663bd0d25b7e608891384b7298). Regardless, the body should probably be encoded before [sending](https://github.com/codecov/codecov-python/blob/master/codecov/__init__.py#L717).

**Comment by stevepeak** [comment]
Hey @JordonPhillips thank you for pointing this out. Would the correct change be

```diff
- s3 = requests.put(upload_url, data=reports,
+ s3 = requests.put(upload_url, data=reports.encode('utf-8'),
```

Thank you!

```

**Comment by JordonPhillips** [comment]
That should work, though I was unable to get a test environment  properly set up so I can't verify. You can reproduce the error by introducing a test whose name has a unicode character, such as `u'\u2713'` (✓), and running codecov on the output from python 3.

**Comment by laedit** [comment]
Same here in a .net project with an in-memory assembly starting by `ℛ`.
The bad side is that every reference to this assembly is filtered from the code coverage and shouldn't be send to CodeCov.

```
==> Detecting CI provider
    AppVeyor Detected
==> Preparing upload
XX> Skip processing gcov
==> Collecting reports
    Targeting specific files
    + coverage.xml bytes=106205
==> Uploading
    .url https://codecov.io
    .query job=[redacted]
    Pinging Codecov...
    Uploading to S3...
Error: 'latin-1' codec can't encode character '\u211b' in position 95631: ordinal not in range(256)
```

The coverage file [link](https://ci.appveyor.com/api/buildjobs/7v78ym8vkvu5mhqx/artifacts/coverage.xml).

If the fix is already made, is it possible to test it?

**Comment by jmanela** [comment]
Is anyone putting up a PR for this?

**Comment by laedit** [comment]
I haven't checked if the issue was still here, but I plan to switch to [codecov/codecov-exe](https://github.com/codecov/codecov-exe) since I don't always have python on the env I use.

**Comment by chfast** [comment]
I had the same issue, but this seemed to help: https://github.com/codecov/codecov-python/pull/124.

**Comment by stevepeak** [comment]
I'll get this deployed asap. Thanks for helping out!
