### ISSUE TITLE
Version 2.0.6 not on PyPI

### ISSUE THREAD

**Issue by wbond** [codecov/codecov-python#89]
Just a reminder that PyPI only has the old version 2.0.5 available: https://pypi.python.org/pypi/codecov

**Comment by vmuriart** [comment]
@wbond you probably know this, but for anyone else wanting to use the new features introduced in `v2.0.6` you can use `pip install https://github.com/codecov/codecov-python/tarball/v2.0.6` as a work-around.

In Travis it would look like:
```yaml
# install: ...
# script: ...

after_success:
  # codecov v2.0.6 isn't on PyPi
  - pip install https://github.com/codecov/codecov-python/tarball/v2.0.6
  - codecov
```

**Comment by jayvdb** [comment]
ping @stevepeak

**Comment by jakirkham** [comment]
cc @CJ-Wright

**Comment by CJ-Wright** [comment]
This should be up on conda-forge soon so you might be able to get it from there.

**Comment by stevepeak** [comment]
We are now on v2.0.10. Let's make sure this version (and subsequent versions) are used moving forward. Upcoming v2.1.0 will have gzipping which is important. 
Thanks!
