### ISSUE TITLE
Add support for local .git repositories not yet published to github that are on Windows.

### ISSUE THREAD

**Issue by AraHaan** [codecov/codecov-python#91]
Currently I can ``pip install --upgrade codecov`` on windows.

However I would like to be able to check the coverage of my latest commits locally so I know weather or not I need to add my tests for some test cases before  I put the repository to github. Is there a way to do this? I can do ``"%SystemDrive%\Python360\python.exe" setup.py test`` that runs pytest and passes the one test the local repository has. I just would like to use this to see how many lines are covered locally and then print the % of the code that is covered.

This is also to ensure proper setup for codecov as well.

Also on travis I see projects like aiohttp doing ``make cov-dev-full``. How can I do that in terms of Windows or AppVeyor when it is on github officially?

**Comment by stevepeak** [comment]
Codecov requires projects to be on GitHub, GitLab or Bitbucket. Codecov does not store source code and uses service API's to integrate with the project. 

In the future we plan to support more local development, but at this time it is not supported.

Thank you!
Steve
