### ISSUE TITLE
TST: pytest?

### ISSUE THREAD

**Issue by CJ-Wright** [codecov/codecov-python#92]
Is there any interest to moving to pytest?

**Comment by stevepeak** [comment]
Codecov does support pytest. Are you asking to move the unit tests for this repo to pytest?

**Comment by CJ-Wright** [comment]
Yes I was asking about moving from unit tests to pytest.

**Comment by stevepeak** [comment]
I'm ok with that. But it would not be high on my priority list. I welcome a PR though.
