### ISSUE TITLE
Include licence file

### ISSUE THREAD

**Issue by CJ-Wright** [codecov/codecov-python#95]
Would it be possible to include a licence file (also in the MANIFEST.in)?

**Comment by hugovk** [comment]
A licence was added in https://github.com/codecov/codecov-python/commit/0fafbb013d14d8ceaae995bc8d069e7af66d627b.

**Comment by CJ-Wright** [comment]
Can you please include it in the release?

**Comment by stevepeak** [comment]
Added to repository. Can you suggest how to add it to the release?

**Comment by thomasrockhu** [comment]
Solved via https://github.com/codecov/codecov-python/blob/76b4f7cbb5602332eac3bcae027b9fa24efbf4ac/codecov/__version__.py#L5
