### ISSUE TITLE
Failing on GitLab CI v9+

### ISSUE THREAD

**Issue by althonos** [codecov/codecov-python#96]
Hi !

So GitLab-CI has been updating from v8 to v9 lately, and they transitioned from *builds* to *job* in their whole nomenclature. As such, some job variables have been renamed, causing `codecov` to crash when called in the CI environment. For instance (this example is actually what makes it crash for me) `CI_BUILD_REPO` has been renamed `CI_REPOSITORY_URL`, so I get the following exception when I try to report:
```shell
      _____          _
     / ____|        | |
    | |     ___   __| | ___  ___ _____   __
    | |    / _ \ / _  |/ _ \/ __/ _ \ \ / /
    | |___| (_) | (_| |  __/ (_| (_) \ V /
     \_____\___/ \____|\___|\___\___/ \_/
                                    v2.0.7

==> Detecting CI provider
Traceback (most recent call last):
  File "/usr/local/bin/codecov", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/codecov/__init__.py", line 473, in main
    slug=os.getenv('CI_BUILD_REPO').split('/', 3)[-1].replace('.git', ''),
AttributeError: 'NoneType' object has no attribute 'split'
ERROR: Job failed: exit code 1
```

I'll submit a PR shortly.

**Comment by jayvdb** [comment]
It can be worked around by adding the following to `.gitlab-ci.yml`
```yaml
variables:
  CI_BUILD_REF_NAME: $CI_COMMIT_REF_NAME
  CI_BUILD_ID: $CI_JOB_ID
  CI_BUILD_REPO: $CI_REPOSITORY_URL
  CI_BUILD_REF: $CI_COMMIT_SHA
```

**Comment by stevepeak** [comment]
Thank you! Will patch today 👍

**Comment by althonos** [comment]
@stevepeak: please see PR (#97), the fix you made will get you the right stub but neither the SHA of the commit nor the right branch...
